name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  php-cs-fixer:
    name: Check PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php --diff --dry-run

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse

  ci:
    name: Test PHP ${{ matrix.php-version }} ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        composer-flags: [""]
        name: [""]
        include:
          - php-version: "8.2"
            composer-flags: "--prefer-lowest"
            name: "(prefer lowest dependencies)"

    services:
      consul:
        image: hashicorp/consul:2.0
        env:
          CONSUL_LOCAL_CONFIG: '{"acl":{"enabled":true,"default_policy":"allow","tokens":{"initial_management":"root"}}}'
        ports:
          - 8500:8500

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: xml

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction ${{ matrix.composer-flags }}

      - name: Run Tests
        run: make test-phpunit
